config/routes.rb
Rails.application.routes.draw do
  get 'cities/:state', to: 'application#cities'

  get 'companies/search_by_city' => 'companies#search_by_city'
  resources :companies
  resources :vacancies
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }
 
 
  root 'profiles#new'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
 validates_length_of :contact, minimum: 10
 validates :name, presence: true
 validates :mark_10th,    :numericality => true
 def a_method_used_for_validation_purposes
    errors[:gra_mark] = "cannot contain the characters !@#%*()_-+="
 end
validate :any_present?
def any_present?
  if %w(name contact graduation).all?{|attr| self[attr].blank?}
    errors.add :base, "Error message"
  end
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :address, :contact, :mark_10th, :mark_12th, :graduation, :gra_mark, :post_graduation, :post_gra_mark)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :class => "form-horizontal profile" } do |f| %>

  <% if @profile.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>
  <div class="form-group">
    <%= f.label :mark_10th, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mark_10th, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mark_10th) %>
  </div>
  <div class="form-group">
    <%= f.label :mark_12th, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mark_12th, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mark_12th) %>
  </div>
  <div class="form-group">
    <%= f.label :graduation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :graduation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:graduation) %>
  </div>
  <div class="form-group">
    <%= f.label :gra_mark, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gra_mark, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gra_mark) %>
  </div>
  <div class="form-group">
    <%= f.label :post_graduation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :post_graduation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:post_graduation) %>
  </div>
  <div class="form-group">
    <%= f.label :post_gra_mark, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :post_gra_mark, :class => 'form-control' %>
    </div>
    <%=f.error_span(:post_gra_mark) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                profiles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<% if current_user.has_role?(:admin)%>
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      <th><%= model_class.human_attribute_name(:mark_10th) %></th>
      <th><%= model_class.human_attribute_name(:mark_12th) %></th>
      <th><%= model_class.human_attribute_name(:graduation) %></th>
      <th><%= model_class.human_attribute_name(:gra_mark) %></th>
      <th><%= model_class.human_attribute_name(:post_graduation) %></th>
      <th><%= model_class.human_attribute_name(:post_gra_mark) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.id, profile_path(profile) %></td>
        <td><%= profile.name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.contact %></td>
        <td><%= profile.mark_10th %></td>
        <td><%= profile.mark_12th %></td>
        <td><%= profile.graduation %></td>
        <td><%= profile.gra_mark %></td>
        <td><%= profile.post_graduation %></td>
        <td><%= profile.post_gra_mark %></td>
        <td><%=l profile.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_profile_path(profile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      profile_path(profile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>
  <%= link_to "create new company",new_company_path, :class => 'btn btn-primary' %>          
<% end %>

<%= link_to 'click here to search city  for vacancy',companies_path, :class => 'btn btn-primary' %>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Name) %>:</strong></dt>
  <dd><%= @profile.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Address) %>:</strong></dt>
  <dd><%= @profile.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Contact) %>:</strong></dt>
  <dd><%= @profile.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Mark_10th) %>:</strong></dt>
  <dd><%= @profile.mark_10th %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Mark_12th) %>:</strong></dt>
  <dd><%= @profile.mark_12th %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Graduation) %>:</strong></dt>
  <dd><%= @profile.graduation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Graduation_mark) %>:</strong></dt>
  <dd><%= @profile.gra_mark %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Post_graduation) %>:</strong></dt>
  <dd><%= @profile.post_graduation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Post_Graduation_mark) %>:</strong></dt>
  <dd><%= @profile.post_gra_mark %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              profiles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_profile_path(@profile), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              profile_path(@profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<%= link_to t('.Createcompany', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>