config/routes.rb
Rails.application.routes.draw do
  get 'cities/:state', to: 'application#cities'

  get 'companies/search_by_city' => 'companies#search_by_city'
  resources :companies
  resources :vacancies
  resources :profiles
  devise_for :users, :controllers => { registrations: 'registrations' }
 
 
  root 'profiles#new'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :vacancies, dependent: :destroy
	
  	validates :name, presence: true
 	validates :contact, :numericality => true
 	validates_length_of :contact, minimum: 10
  	validates :pincode, :numericality => true

  

  def  match_zip
	geo = GeoKit::Geocoders::MultiGeocoder.multi_geocoder('90210')
	if geo.success
  	geo.state # => CA
  	geo.city  # => Beverly Hills
	end
 end
 def city_state
 	 State.all.map do |s| 
      cities = s.cities.map.with_index(1){|c, i| {i.to_s => c.name}}
      {
        :state => s.name, 
        :cities => cities
    }
end
 end


	def self.search(search)
	  #where("city ILIKE ?","%#{search}%")
	  where("city LIKE ?", "%#{search}%") 

 	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  def cities
    render json: CS.cities(params[:state], :us).to_json
  end

  def search_by_city
    if params[:search]
      @companies = Company.search(params[:search]).order("created_at DESC")
    else
      @companies= Company.all.order('created_at DESC')
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
   @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
    if @company.save
      format.html { redirect_to @company, notice: 'Company was successfully created.' }
      format.json { render :show, status: :created, location: @company }
    else
      format.html { render :new }
      format.json { render json: @company.errors, status: :unprocessable_entity }
    end
  end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
    if @company.update(company_params)
      format.html { redirect_to @company, notice: 'Company was successfully updated.' }
      format.json { render :show, status: :ok, location: @company }
    else
      format.html { render :edit }
      format.json { render json: @company.errors, status: :unprocessable_entity }
    end
  end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:search,:name, :address, :contact, :city, :state, :pincode)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => "form-horizontal company" } do |f| %>

  <% if @company.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>
    </div>
    <div class="panel-body">
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :address, :class => 'form-control' %>
  </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :contact, :class => 'form-control' %>
  </div>
    <%=f.error_span(:contact) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :city, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
   <div class="col-lg-10">
    <%= f.text_field :state, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :pincode, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :pincode, :class => 'form-control' %>
  </div>
    <%=f.error_span(:pincode) %>
  </div>
  <div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            companies_path, :class => 'btn btn-default' %>
  </div>
  </div>

<% end %>

 

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<% if current_user.has_role?(:admin)%>
  <%- model_class = Company -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:address) %></th>
        <th><%= model_class.human_attribute_name(:contact) %></th>
        <th><%= model_class.human_attribute_name(:city) %></th>
        <th><%= model_class.human_attribute_name(:state) %></th>
        <th><%= model_class.human_attribute_name(:pincode) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
          <tr>
          <td><%= company.name %></td>
          <td><%= company.address %></td>
          <td><%= company.contact %></td>
          <td><%= company.city %></td>
          <td><%= company.state %></td>
          <td><%= company.pincode %></td>
          <td><%=l company.created_at %></td>
          <td><%= link_to t('.edit', :default => t("helpers.links.edit")),edit_company_path(company), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),company_path(company), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %>
             <% end %>
          </tr>
     </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),new_company_path, :class => 'btn btn-primary' %>
<% end %>

  <%= form_tag(companies_search_by_city_path, :method => "get", id: "new-post") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by city",required: true %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/search_by_city.html.erb
<% if @companies.present? %>
  <table class="table table-bordered table-hover table-striped", class: "btn btn-primary">
  	<tr>     
  		<th>Company Name</th>
    	<th>Post Name</th>
        <th>No. of Vacancy</th>
        <th>Technology</th>
        <th>Eligibility</th>
        <th>key Skills</th>
        <th>Location</th>
        <th>Experence</th>
        <th>Salry</th>
    	<th colspan:'3'></th>
    	</tr>
    <% @companies.each do |company| %>
      	<% if company.vacancies.count > 0 %>
	        <% company.vacancies.each do |vacancy| %>
	          <tr>
	          	<td><%= company.name%> </td>
	            <td><%= vacancy.name %></td>
	            <td><%= vacancy.no_of_vacancy%> </td>
	            <td><%= vacancy.technology%> </td>
	            <td><%= vacancy.eligibilty%> </td>
	            <td><%= vacancy.key_skilles%> </td>
	            <td><%= vacancy.company.city%>(<%= vacancy.company.state%>)</td>
	             <td><%= vacancy.experience%> </td>
	             <td><%= vacancy.salary%> </td>

	          </tr>
	    	<% end %>
    	<% else %>
    		<tr>
      			<td colspan="2">No vacancies found for this company.  Click the 'New Picture' button to create a new picture.</td>
    		</tr>
  		<% end %>
  	<% end %>	
    </table>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>
<%= link_to 'Back', companies_path, class: "btn btn-default" %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @company.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @company.contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @company.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @company.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pincode) %>:</strong></dt>
  <dd><%= @company.pincode %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              companies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_path(@company), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),company_path(@company),:method => 'delete',:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },:class => 'btn btn-danger' %>
<%= link_to "create vacancy",
               new_vacancy_path, :class => 'btn btn-default'  %>